### PR TITLE
Fix Revolver Icon to not use Desert Eagle URL.

### LINKED ISSUE #27: R8 Revolver gets displayed as Desert Eagle
If a player is using a "R8 Revolver" the HUD displays a "Desert Eagle" icon instead of the correct icon for the revolver. 
r8

It's a minor issue since only a few players are actually buying this pistol, but I thought you might want to know about this bug.

kind regards! :)

### PR DESCRIPTION
**Pull request by bergmannf**
This should fix #27

### CODE REVIEW

File: src/views/player/Story.tsx [hunk 1]
```diff
@@ -32,9 +32,12 @@ const props: PlayerProps = {
...
-};
+});
 
 storiesOf("Player", module)
     .add("プレイヤー情報を表示できる", () => {
-        return <Player {...props} />;
+        return <Player {...props()} />;
+    })
+    .add("Player-Revolver", () => {
+        return <Player {...props("weapon_m4a1", "weapon_revolver")} />;
```
Comment (Thiry1) [inline src/views/player/Story.tsx]: 👍
